export const rejectTexts = [
  "Reject 💔",
  "Wait… really sure? 🥺",
  "My heart hoped otherwise 💕",
  "Take a breath with me 🌸",
 "Some moments deserve courage ✨",
  "This could be something beautiful 💖",

  "Love is standing quietly here 💓",
  "One yes can change forever 🌹",
  "Don’t let fear decide ❣️",
  "My heart is still open 😔",
  "I’m waiting, gently 💌",
  "Even doubts feel like love 💭",
  "Maybe you feel it too 💞",
  "Love feels scary sometimes 💔",
  "But magic begins there ✨",
  "Please don’t rush this 🕊️",
  "My heartbeat says stay 😢",

  "This choice feels heavy 💘",
  "Hope is fading slowly ❄️",
  "I imagined us smiling 💑",
  "Are you truly certain? 😞",
  "This silence feels loud 💭",
  "Love shouldn’t feel distant 💔",
  "I was ready for always 🌙",
  "My heart is holding on 🥀",
  "I wish you felt this warmth 💞",
  "This hurts more than expected 😔",
  "Please… don’t walk away 💔",
  "I’m barely holding together 😢",
  "This moment decides everything 💔",

  "I guess love wasn’t enough 😞",
  "My heart will remember you 💔",
  "Some feelings fade quietly 🥀",
  "I’ll miss what we dreamed 😢",
  "Love stayed, you left 💭",
  "Silence became my answer 😔",
  "I’ll carry this softly 💔",
  "Maybe in another lifetime 🌙",
  "I hoped you were forever 🥀",
  "Goodbye, my almost love 💔"
]